### 1. Load Data

In [4]:
import pandas as pd
import numpy as np

df = pd.read_csv('raw_data.csv')
df.head()

,Order_ID,Warehouse,Customer_City,Payment_Method,Brand_Name,Raw_Product_Title,Order_Value_INR,Hours_to_Dispatch,Order_Status
0,10528,WH-103 (Blru),NaN,COD,stepwell,Premium Running Sneakers,2138.4,27,Delivered
1,10360,WH-104 (Kolkat),Patna,Prepaid,StepWell,Premium Running Sneakers,1692.71,18,Delivered
2,10448,WH-103 (Blru),Lucknow,Prepaid,ZariBrands,Fancy Designer Georgette Pink Saree,4464.48,9,Delivered
3,10032,WH-101 (Mumb),Ranchi,Prepaid,KicksCo,Unisex Running Joggers,2570.47,4,Delivered
4,10622,WH-104 (Kolkat),NaN,Prepaid,ElectroTech,Smart Watch Series 5,3891.0,54,Delivered

### 2. Identify and Remove Duplicates

In [5]:
# Check duplicate count
display(df.duplicated().sum())

# Remove duplicates
df = df.drop_duplicates()

np.int64(25)

### 3. Explore and Standardize Categories

In [6]:
# Check unique values of payment method
display(df['Payment_Method'].unique())

array(['COD', 'Prepaid', 'C.O.D.', 'cod', 'Cash on Delivery', 'Cash'],
      dtype=object)

In [8]:
# Standardize Payment Methods
payment_map = {'C.O.D.': 'COD', 'cod': 'COD', 'Cash on Delivery': 'COD', 'Cash': 'COD'}
df['Payment_Method'] = df['Payment_Method'].replace(payment_map)

In [9]:
# Check unique values of cities
display(df['Customer_City'].unique())

array([nan, 'Patna', 'Lucknow', 'Ranchi', 'Delhi', 'Indore', 'Guwahati',
       'Bangalore', 'mumbai', 'Mumbai', 'lucknow', 'bengaluru', 'Bnglr',
       'Bengaluru', 'ranchi', 'LKO', 'MUM', 'Mumbay'], dtype=object)

In [13]:
# Standardize Cities
df['Customer_City'] = df['Customer_City'].replace(['mumbai', 'MUM', 'Mumbay'], 'Mumbai')
df['Customer_City'] = df['Customer_City'].replace(['lucknow', 'LKO'], 'Lucknow')
df['Customer_City'] = df['Customer_City'].replace(['bengaluru', 'Bengaluru', 'Bnglr'], 'Bangalore')
df['Customer_City'] = df['Customer_City'].replace(['ranchi'], 'Ranchi')

In [11]:
# Clean formatting
df['Warehouse'] = df['Warehouse'].str.strip()
df['Brand_Name'] = df['Brand_Name'].str.title()

In [14]:
df

,Order_ID,Warehouse,Customer_City,Payment_Method,Brand_Name,Raw_Product_Title,Order_Value_INR,Hours_to_Dispatch,Order_Status
0,10528,WH-103 (Blru),NaN,COD,Stepwell,Premium Running Sneakers,2138.4,27,Delivered
1,10360,WH-104 (Kolkat),Patna,Prepaid,Stepwell,Premium Running Sneakers,1692.71,18,Delivered
2,10448,WH-103 (Blru),Lucknow,Prepaid,Zaribrands,Fancy Designer Georgette Pink Saree,4464.48,9,Delivered
3,10032,WH-101 (Mumb),Ranchi,Prepaid,Kicksco,Unisex Running Joggers,2570.47,4,Delivered
4,10622,WH-104 (Kolkat),NaN,Prepaid,Electrotech,Smart Watch Series 5,3891.0,54,Delivered
...,...,...,...,...,...,...,...,...,...
1020,10701,WH-102 (Delh),Ranchi,COD,Desiweaves,Cotton Palazzo Pants Casual,1095.73,11,Delivered
1021,10072,WH-103 (Blru),Guwahati,Prepaid,Stepwell,Casual Daily Wear Sandals,638.43,16,Returned
1022,10107,WH-104 (Kolkat),Lucknow,Prepaid,Stepwell,Formal Leather Shoes Men,2273.63,30,Returned
1023,10271,WH-102 (Delh),Patna,COD,Desiweaves,Designer Chikankari Kurta Luxury,2655.72,19,Delivered
1024,10861,WH-102 (Delh),Indore,COD,NaN,Fancy Designer Georgette Pink Saree,1151.09,14,Delivered

### 4. Explore and Fix Numerical Errors

In [15]:
# Check for impossible negative time values
display((df['Hours_to_Dispatch'] < 0).sum())

np.int64(15)

In [16]:
# Fix negatives with absolute values
df['Hours_to_Dispatch'] = df['Hours_to_Dispatch'].abs()

In [18]:
# Fix string numbers (e.g. '1,500.00')
df['Order_Value_INR'] = df['Order_Value_INR'].astype(str).str.replace(',', '').astype(float)

In [19]:
# Fix negatives with absolute values
df['Order_Value_INR'] = df['Order_Value_INR'].abs()

In [20]:
# Cap massive outliers
df.loc[df['Order_Value_INR'] > 100000, 'Order_Value_INR'] = np.nan

In [21]:
df

,Order_ID,Warehouse,Customer_City,Payment_Method,Brand_Name,Raw_Product_Title,Order_Value_INR,Hours_to_Dispatch,Order_Status
0,10528,WH-103 (Blru),NaN,COD,Stepwell,Premium Running Sneakers,2138.40,27,Delivered
1,10360,WH-104 (Kolkat),Patna,Prepaid,Stepwell,Premium Running Sneakers,1692.71,18,Delivered
2,10448,WH-103 (Blru),Lucknow,Prepaid,Zaribrands,Fancy Designer Georgette Pink Saree,4464.48,9,Delivered
3,10032,WH-101 (Mumb),Ranchi,Prepaid,Kicksco,Unisex Running Joggers,2570.47,4,Delivered
4,10622,WH-104 (Kolkat),NaN,Prepaid,Electrotech,Smart Watch Series 5,3891.00,54,Delivered
...,...,...,...,...,...,...,...,...,...
1020,10701,WH-102 (Delh),Ranchi,COD,Desiweaves,Cotton Palazzo Pants Casual,1095.73,11,Delivered
1021,10072,WH-103 (Blru),Guwahati,Prepaid,Stepwell,Casual Daily Wear Sandals,638.43,16,Returned
1022,10107,WH-104 (Kolkat),Lucknow,Prepaid,Stepwell,Formal Leather Shoes Men,2273.63,30,Returned
1023,10271,WH-102 (Delh),Patna,COD,Desiweaves,Designer Chikankari Kurta Luxury,2655.72,19,Delivered
1024,10861,WH-102 (Delh),Indore,COD,NaN,Fancy Designer Georgette Pink Saree,1151.09,14,Delivered

### 5. Explore and Impute Missing Values

In [22]:
# Check null counts across all columns
display(df.isnull().sum())

Order_ID              0
Warehouse             0
Customer_City        80
Payment_Method        0
Brand_Name           30
Raw_Product_Title     0
Order_Value_INR      55
Hours_to_Dispatch     0
Order_Status          0
dtype: int64

In [23]:
# Impute missing categories
df['Customer_City'] = df['Customer_City'].fillna('Unknown')

In [24]:
df['Brand_Name'] = df['Brand_Name'].fillna('Unknown')

In [25]:
# Impute numerical blanks with median
df['Order_Value_INR'] = df['Order_Value_INR'].fillna(df['Order_Value_INR'].median())

In [26]:
df

,Order_ID,Warehouse,Customer_City,Payment_Method,Brand_Name,Raw_Product_Title,Order_Value_INR,Hours_to_Dispatch,Order_Status
0,10528,WH-103 (Blru),Unknown,COD,Stepwell,Premium Running Sneakers,2138.40,27,Delivered
1,10360,WH-104 (Kolkat),Patna,Prepaid,Stepwell,Premium Running Sneakers,1692.71,18,Delivered
2,10448,WH-103 (Blru),Lucknow,Prepaid,Zaribrands,Fancy Designer Georgette Pink Saree,4464.48,9,Delivered
3,10032,WH-101 (Mumb),Ranchi,Prepaid,Kicksco,Unisex Running Joggers,2570.47,4,Delivered
4,10622,WH-104 (Kolkat),Unknown,Prepaid,Electrotech,Smart Watch Series 5,3891.00,54,Delivered
...,...,...,...,...,...,...,...,...,...
1020,10701,WH-102 (Delh),Ranchi,COD,Desiweaves,Cotton Palazzo Pants Casual,1095.73,11,Delivered
1021,10072,WH-103 (Blru),Guwahati,Prepaid,Stepwell,Casual Daily Wear Sandals,638.43,16,Returned
1022,10107,WH-104 (Kolkat),Lucknow,Prepaid,Stepwell,Formal Leather Shoes Men,2273.63,30,Returned
1023,10271,WH-102 (Delh),Patna,COD,Desiweaves,Designer Chikankari Kurta Luxury,2655.72,19,Delivered
1024,10861,WH-102 (Delh),Indore,COD,Unknown,Fancy Designer Georgette Pink Saree,1151.09,14,Delivered

### 6. Save Final Dataset

In [27]:
df.to_csv('cleaned_data.csv', index=False)
df.head()

,Order_ID,Warehouse,Customer_City,Payment_Method,Brand_Name,Raw_Product_Title,Order_Value_INR,Hours_to_Dispatch,Order_Status
0,10528,WH-103 (Blru),Unknown,COD,Stepwell,Premium Running Sneakers,2138.40,27,Delivered
1,10360,WH-104 (Kolkat),Patna,Prepaid,Stepwell,Premium Running Sneakers,1692.71,18,Delivered
2,10448,WH-103 (Blru),Lucknow,Prepaid,Zaribrands,Fancy Designer Georgette Pink Saree,4464.48,9,Delivered
3,10032,WH-101 (Mumb),Ranchi,Prepaid,Kicksco,Unisex Running Joggers,2570.47,4,Delivered
4,10622,WH-104 (Kolkat),Unknown,Prepaid,Electrotech,Smart Watch Series 5,3891.00,54,Delivered